# Uncomment and use this with `cargo +nightly fmt`:
# unstable_features = true
# format_code_in_doc_comments = true
edition = "2018"
# indent_style = "Block"
reorder_imports = true
merge_imports = true